#+TITLE: Docker Emacs

This =Dockerfile= creates a sandboxed, runnable [[https://orgmode.org/][Org-mode]] environment built with the =archlinux/base= image package and [[https://www.gnu.org/software/emacs/][GNU Emacs]] installed.

Pull this image from [[https://hub.docker.com/r/padawanphysicist/nikola/][Docker Hub]] with the command =docker pull padawanphysicist/emacs=.

* Contains
This comes with the following software:
- GNU Emacs 26.2
- Org mode version 9.2.3

Since its only dependency is Docker, it should run on any platform with Docker installed. It may or may not work with earlier versions of docker.  To install docker on your system, see the [[https://docs.docker.com/installation][official docker installation instructions]].

* Installation
To pull the docker image. (Depending on your connection speed this is likely much faster than building your own):
#+BEGIN_SRC sh
$ docker pull padawanphysicist/emacs
#+END_SRC

Alternatively to pulling the docker image build the docker image with:
#+BEGIN_SRC sh
$ docker build -t padawanphysicist/emacs gitlab.com/padawanphysicist/docker-emacs
#+END_SRC

You can see your new image that you either pulled or built with this command:
#+BEGIN_SRC sh
$ docker images
#+END_SRC


